#!/bin/bash

# .bashrc is ran during an interactive shell, eg bash -i
# it is not ran during a login shell, eg bash -l (unless sourced by .bash_profile)

# Get execution time of each command - Useful for debugging why bashrc is slow
# N=$(date +%s%N)
# export PS4='+[$(((`date +%s%N`-$N)/1000000))ms][${BASH_SOURCE}:${LINENO}]: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
# set -x

# Run all scripts in ~/.bashrc.d/ that have a .always.bashrc extension
# shellcheck disable=SC1090
for file in ~/.bashrc.d/*.always.bashrc; do
  source "$file"
done

# If we're in an interactive shell, run special scripts in ~/.bashrc.d/ that have a .interactive.bashrc extension
# shellcheck disable=SC1090
if [[ $- == *i* ]]; then
  for file in ~/.bashrc.d/*.interactive.bashrc; do
    source "$file"
  done
fi
