version: '3.3'
services:

  service:
    image: 'sourcegraph/server:5.1.8'
    restart: always
    ports:
      - '7080:7080'
      - '3370:3370'
    volumes:
      - './config:/etc/sourcegraph'
      - './data:/var/opt/sourcegraph'
